#!/bin/bash

DRIVERS="
xf86-input-egalax
xf86-input-elographics
xf86-input-evdev
xf86-input-joystick
xf86-input-keyboard
xf86-input-libinput
xf86-input-mouse
xf86-input-synaptics
xf86-input-vmmouse
xf86-input-void
xf86-input-wacom
xf86-video-amdgpu
xf86-video-apm
xf86-video-ark
xf86-video-ast
xf86-video-ati
xf86-video-chips
xf86-video-cirrus
xf86-video-dummy
xf86-video-fbdev
xf86-video-freedreno
xf86-video-geode
xf86-video-i128
xf86-video-i740
xf86-video-intel
xf86-video-mach64
xf86-video-mga
xf86-video-neomagic
xf86-video-nested
xf86-video-nouveau
xf86-video-nv
xf86-video-omap
xf86-video-openchrome
xf86-video-qxl
xf86-video-r128
xf86-video-rendition
xf86-video-s3virge
xf86-video-savage
xf86-video-scfb
xf86-video-siliconmotion
xf86-video-sis
xf86-video-sisusb
xf86-video-suncg14
xf86-video-suncg3
xf86-video-suncg6
xf86-video-sunffb
xf86-video-sunleo
xf86-video-suntcx
xf86-video-tdfx
xf86-video-trident
xf86-video-v4l
xf86-video-vbox
xf86-video-vesa
xf86-video-vmware
xf86-video-voodoo
xf86-video-wsfb
xf86-video-xgi
"

for  d in $DRIVERS ; do
    ~/go/bin/mpbt-builder \
        -root . \
        -solution .mpbt/cf/xlibre/solutions/github-drivers.yaml \
        -solution-define build=xserver/$d \
        -workdir _WORK_ \
        build
done

#    -solution-define build=xserver/xf86-input-elographics \
