#!/bin/bash

~/go/bin/mpbt-builder \
    -root . \
    -solution .mpbt/cf/xlibre/solutions/github-drivers.yaml \
    -solution-define build=xserver/xf86-input-elographics \
    -workdir _WORK_ \
    build
